// src/redux/types.js
export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSE_DETAILS = 'FETCH_COURSE_DETAILS';
export const FETCH_USER_COURSES = 'FETCH_USER_COURSES';
export const MARK_COURSE_COMPLETE = 'MARK_COURSE_COMPLETE';

